### PR TITLE
set canvas viewbox based on image upload checkbox value

### PR DESCRIPTION
**Pull request by shepazu**
Attached behavior to checkbox, so user can resize the canvas to match the raster image size.

### CODE REVIEW

**Comment by jcdyer** [comment]
Tried it out with an SVG and a PNG.  Looks good.

**Comment by jcdyer** [comment]
Um.  Some caveats.  

* When I import a PNG, it won't let me draw a circle on top of it.  I have to draw it off the PNG, and then drag it on top.
* If I use a person image, and then download, the source of the person isn't included in the file, just the reference, so it doesn't render when I load the image in my browser.

**Review by jcdyer — APPROVED** [review]
The mentioned issues can be handled separately.  The image upload seems to work.

**Comment by shepazu** [comment]
> When I import a PNG, it won't let me draw a circle on top of it. I have to draw it off the PNG, and then drag it on top.

Which browser/OS? I'm able to draw on top of an imported image in Chrome/MacOSX. I might need access to your computer to debug this.

**Comment by shepazu** [comment]
> If I use a person image, and then download, the source of the person isn't included in the file, just the reference, so it doesn't render when I load the image in my browser.

When you say "person image", do you mean a use/symbol? If so, I know about that issue, and how to fix it, just haven't gotten around to it.

If you mean some other kind of image, please provide more detail.

**Pull request merged**
